name: Rust tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rust-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: cargo test --all-features --lib --bins
